package com.yonagi.verse.dao.mapper;

import com.yonagi.verse.dao.entity.TenantActivityLogDO;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.mybatis.spring.SqlSessionFactoryBean;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

class TenantActivityLogMapperIntegrationTest {

    private EmbeddedDatabase database;
    private JdbcTemplate jdbcTemplate;
    private SqlSession session;
    private TenantActivityLogMapper mapper;

    @BeforeEach
    void setUp() throws Exception {
        database = new EmbeddedDatabaseBuilder()
                .generateUniqueName(true)
                .setType(EmbeddedDatabaseType.H2)
                .build();
        jdbcTemplate = new JdbcTemplate(database);
        jdbcTemplate.execute("""
                CREATE TABLE t_tenant_activity_log (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_id VARCHAR(64) NOT NULL UNIQUE,
                    tenant_id BIGINT NOT NULL,
                    category VARCHAR(32) NOT NULL,
                    activity_type VARCHAR(64) NOT NULL,
                    actor_user_id BIGINT NOT NULL,
                    actor_username VARCHAR(64) NOT NULL,
                    actor_nickname VARCHAR(100),
                    target_type VARCHAR(32),
                    target_id VARCHAR(64),
                    target_name VARCHAR(255),
                    detail_json VARCHAR(2000) NOT NULL,
                    schema_version INT NOT NULL,
                    occurred_at TIMESTAMP(3) NOT NULL,
                    create_time TIMESTAMP(3) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE INDEX idx_tenant_activity_timeline
                ON t_tenant_activity_log(tenant_id, occurred_at DESC, id DESC)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE t_user (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL UNIQUE,
                    username VARCHAR(50) NOT NULL UNIQUE,
                    nickname VARCHAR(50) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE t_user_tenant (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    tenant_id BIGINT NOT NULL,
                    left_at TIMESTAMP NULL,
                    UNIQUE (user_id, tenant_id)
                )
                """);

        SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
        factoryBean.setDataSource(database);
        org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
        configuration.setMapUnderscoreToCamelCase(true);
        configuration.addMapper(TenantActivityLogMapper.class);
        factoryBean.setConfiguration(configuration);
        SqlSessionFactory factory = factoryBean.getObject();
        session = factory.openSession();
        mapper = session.getMapper(TenantActivityLogMapper.class);
    }

    @AfterEach
    void tearDown() {
        if (session != null) {
            session.close();
        }
        database.shutdown();
    }

    @Test
    void queryIsTenantIsolatedStableAndDoesNotSkipAcrossCursor() {
        LocalDateTime sameTime = LocalDateTime.of(2026, 9, 19, 12, 0);
        insert("tenant-20-older", 20L, sameTime.minusSeconds(1));
        insert("tenant-20-same-first", 20L, sameTime);
        insert("other-tenant", 21L, sameTime.plusHours(1));
        insert("tenant-20-same-second", 20L, sameTime);

        List<TenantActivityLogDO> first = mapper.selectTimeline(20L, null, null, 3);
        assertEquals(List.of("tenant-20-same-second", "tenant-20-same-first", "tenant-20-older"),
                first.stream().map(TenantActivityLogDO::getEventId).toList());

        TenantActivityLogDO cursorRow = first.get(1);
        List<TenantActivityLogDO> second = mapper.selectTimeline(
                20L, cursorRow.getOccurredAt(), cursorRow.getId(), 3);
        assertEquals(List.of("tenant-20-older"),
                second.stream().map(TenantActivityLogDO::getEventId).toList());
    }

    @Test
    void queryUsesCurrentNicknameWhileActorIsMemberAndSnapshotAfterLeaving() {
        LocalDateTime occurredAt = LocalDateTime.of(2026, 9, 19, 12, 0);
        insert("nickname-event", 20L, occurredAt);
        jdbcTemplate.update(
                "INSERT INTO t_user(user_id, username, nickname) VALUES (10, 'alice', '当前昵称')");
        jdbcTemplate.update(
                "INSERT INTO t_user_tenant(user_id, tenant_id, left_at) VALUES (10, 20, NULL)");

        TenantActivityLogDO currentMemberRow = mapper.selectTimeline(20L, null, null, 1).getFirst();
        assertEquals("当前昵称", currentMemberRow.getCurrentActorNickname());
        assertEquals("快照昵称", currentMemberRow.getActorNickname());

        jdbcTemplate.update("UPDATE t_user SET nickname = '更新后昵称' WHERE username = 'alice'");
        session.clearCache();
        TenantActivityLogDO renamedMemberRow = mapper.selectTimeline(20L, null, null, 1).getFirst();
        assertEquals("更新后昵称", renamedMemberRow.getCurrentActorNickname());

        jdbcTemplate.update(
                "UPDATE t_user_tenant SET left_at = CURRENT_TIMESTAMP WHERE user_id = 10 AND tenant_id = 20");
        session.clearCache();
        TenantActivityLogDO formerMemberRow = mapper.selectTimeline(20L, null, null, 1).getFirst();
        assertNull(formerMemberRow.getCurrentActorNickname());
        assertEquals("快照昵称", formerMemberRow.getActorNickname());
    }

    private void insert(String eventId, Long tenantId, LocalDateTime occurredAt) {
        jdbcTemplate.update("""
                INSERT INTO t_tenant_activity_log(
                    event_id, tenant_id, category, activity_type, actor_user_id,
                    actor_username, actor_nickname, detail_json, schema_version, occurred_at, create_time)
                VALUES (?, ?, 'TENANT', 'TENANT_SETTINGS_UPDATED', 10,
                        'alice', '快照昵称', '{}', 1, ?, ?)
                """, eventId, tenantId, Timestamp.valueOf(occurredAt), Timestamp.valueOf(occurredAt));
    }
}
