package com.yonagi.verse.async.handler;

import com.yonagi.verse.async.event.TenantActivityEvent;
import com.yonagi.verse.async.outbox.DomainOutboxMetrics;
import com.yonagi.verse.common.enums.TenantActivityCategory;
import com.yonagi.verse.common.enums.TenantActivityType;
import com.yonagi.verse.dao.entity.TenantActivityLogDO;
import com.yonagi.verse.dao.mapper.TenantActivityLogMapper;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class TenantActivityPersistenceIntegrationTest {

    private EmbeddedDatabase database;
    private JdbcTemplate jdbcTemplate;
    private TenantActivityEventHandler handler;

    @BeforeEach
    void setUp() {
        database = new EmbeddedDatabaseBuilder()
                .generateUniqueName(true)
                .setType(EmbeddedDatabaseType.H2)
                .build();
        jdbcTemplate = new JdbcTemplate(database);
        jdbcTemplate.execute("""
                CREATE TABLE tenant_activity_fact (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_id VARCHAR(64) NOT NULL UNIQUE,
                    occurred_at TIMESTAMP(3) NOT NULL
                )
                """);
        TenantActivityLogMapper mapper = mock(TenantActivityLogMapper.class);
        when(mapper.insert(any(TenantActivityLogDO.class))).thenAnswer(invocation -> {
            TenantActivityLogDO row = invocation.getArgument(0);
            return jdbcTemplate.update(
                    "INSERT INTO tenant_activity_fact(event_id, occurred_at) VALUES (?, ?)",
                    row.getEventId(), row.getOccurredAt());
        });
        when(mapper.countByEventId(any())).thenAnswer(invocation -> {
            String eventId = invocation.getArgument(0);
            return jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM tenant_activity_fact WHERE event_id=?",
                    Long.class, eventId);
        });
        handler = new TenantActivityEventHandler(mapper, mock(DomainOutboxMetrics.class));
    }

    @AfterEach
    void tearDown() {
        database.shutdown();
    }

    @Test
    void concurrentDeliveryOfSameEventCreatesOneFact() throws Exception {
        TenantActivityEvent event = event("same-event", 1_700_000_000_123L);
        ExecutorService executor = Executors.newFixedThreadPool(8);
        try {
            CountDownLatch start = new CountDownLatch(1);
            List<Future<?>> futures = new ArrayList<>();
            for (int i = 0; i < 8; i++) {
                futures.add(executor.submit(() -> {
                    start.await();
                    handler.onEvent(event);
                    return null;
                }));
            }
            start.countDown();
            for (Future<?> future : futures) {
                future.get();
            }
        } finally {
            executor.shutdownNow();
        }
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM tenant_activity_fact", Integer.class));
    }

    @Test
    void timelineUsesOccurredAtThenStableIdForDelayedAndSameMillisecondEvents() throws Exception {
        handler.onEvent(event("same-ms-first", 2_000L));
        handler.onEvent(event("same-ms-second", 2_000L));
        handler.onEvent(event("delayed-older", 1_000L));

        List<String> ordered = jdbcTemplate.queryForList(
                "SELECT event_id FROM tenant_activity_fact ORDER BY occurred_at DESC, id DESC",
                String.class);
        assertEquals(List.of("same-ms-second", "same-ms-first", "delayed-older"), ordered);

        String migration = Files.readString(Path.of(
                "src/main/resources/db/migration/V20260919_01__tenant_activity_recording.sql"));
        assertTrue(migration.contains("idx_tenant_activity_timeline (tenant_id,occurred_at DESC,id DESC)"));
    }

    private TenantActivityEvent event(String eventId, long occurredAt) {
        TenantActivityEvent event = new TenantActivityEvent();
        event.setEventId(eventId);
        event.setOccurredAt(occurredAt);
        event.setTenantId(20L);
        event.setKey("20");
        event.setCategory(TenantActivityCategory.TENANT);
        event.setActivityType(TenantActivityType.TENANT_SETTINGS_UPDATED);
        event.setActorUserId(10L);
        event.setActorUsername("alice");
        return event;
    }
}
