package com.yonagi.verse.service.forward;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CapabilityMigrationCompatibilityTest {
    @Test
    void legacyServicesAreBackfilledWithoutChangingRowsAndRollbackPreservesChat() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:capabilities;MODE=MySQL;DB_CLOSE_DELAY=-1")) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("""
                        CREATE TABLE t_llm_service (
                            service_id BIGINT PRIMARY KEY,
                            provider VARCHAR(255) NOT NULL,
                            status INTEGER NOT NULL,
                            api_url VARCHAR(255) NOT NULL,
                            api_key VARCHAR(512) NOT NULL
                        )
                        """);
                statement.execute("""
                        INSERT INTO t_llm_service VALUES
                            (1, 'openai', 1, 'https://example.test/v1', 'encrypted-1'),
                            (2, 'gemini', 0, 'https://example.test/v1', 'encrypted-2'),
                            (3, 'unknown-supplier', 1, 'https://example.test/v1', 'encrypted-3')
                        """);
            }
            // H2 不支持 MySQL 的多列 ALTER/COMMENT 语法；使用等价表结构执行原迁移的回填 SQL。
            try (Statement statement = connection.createStatement()) {
                statement.execute("""
                        CREATE TABLE t_llm_service_capability (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            service_id BIGINT NOT NULL,
                            operation VARCHAR(40) NOT NULL,
                            upstream_protocol VARCHAR(40) NOT NULL,
                            enabled INTEGER NOT NULL,
                            UNIQUE (service_id, operation)
                        )
                        """);
                statement.execute("ALTER TABLE t_llm_service ADD COLUMN credential_mode VARCHAR(32) DEFAULT 'API_KEY'");
                statement.execute("ALTER TABLE t_llm_service ADD COLUMN provider_settings JSON");
                String migration = new String(new ClassPathResource(
                        "db/migration/V20260925_01__model_capability_bindings.sql")
                        .getInputStream().readAllBytes(), StandardCharsets.UTF_8);
                String backfill = migration.substring(migration.indexOf("INSERT INTO t_llm_service_capability"));
                statement.execute(backfill);
                statement.execute(backfill);
            }
            try (Statement statement = connection.createStatement();
                 ResultSet result = statement.executeQuery("""
                         SELECT COUNT(*) FROM t_llm_service_capability
                         WHERE operation='CHAT_COMPLETIONS' AND upstream_protocol='OPENAI_COMPAT' AND enabled=1
                         """)) {
                result.next();
                assertEquals(3, result.getInt(1));
            }
            try (Statement statement = connection.createStatement()) {
                statement.execute("DROP TABLE t_llm_service_capability");
                statement.execute("ALTER TABLE t_llm_service DROP COLUMN provider_settings");
                statement.execute("ALTER TABLE t_llm_service DROP COLUMN credential_mode");
            }
            try (Statement statement = connection.createStatement();
                 ResultSet result = statement.executeQuery("""
                         SELECT COUNT(*), SUM(CASE WHEN provider='unknown-supplier' AND status=1
                             AND api_key='encrypted-3' THEN 1 ELSE 0 END) FROM t_llm_service
                         """)) {
                result.next();
                assertEquals(3, result.getInt(1));
                assertEquals(1, result.getInt(2));
            }
        }
    }
}
