package com.yonagi.verse.service.impl;

import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean;
import com.yonagi.verse.async.activity.TenantActivityRecorder;
import com.yonagi.verse.common.constant.RedisKeyConstant;
import com.yonagi.verse.common.convention.exception.ClientException;
import com.yonagi.verse.common.convention.exception.ServerException;
import com.yonagi.verse.common.enums.TenantErrorCodeEnum;
import com.yonagi.verse.dao.entity.TenantDO;
import com.yonagi.verse.dao.entity.TenantJoinRequestDO;
import com.yonagi.verse.dao.mapper.TenantInviteMapper;
import com.yonagi.verse.dao.mapper.TenantJoinRequestMapper;
import com.yonagi.verse.dao.mapper.UserMapper;
import com.yonagi.verse.dto.req.TenantJoinRejectReqDTO;
import com.yonagi.verse.service.NotificationService;
import com.yonagi.verse.service.TenantApprovalService;
import com.yonagi.verse.service.TenantInviteService;
import com.yonagi.verse.service.UserTenantService;
import com.yonagi.verse.service.helper.TenantValidationHelper;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.aop.framework.ProxyFactory;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.transaction.annotation.AnnotationTransactionAttributeSource;
import org.springframework.transaction.interceptor.TransactionInterceptor;

import java.util.List;
import java.util.Objects;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/** 使用真实 Mapper 验证租户隔离 SQL，外部通知、动态、Redis 和成员服务使用替身。 */
class TenantApprovalServiceImplTest {

    private EmbeddedDatabase database;
    private JdbcTemplate jdbc;
    private TenantJoinRequestMapper requests;
    private UserTenantService memberships;
    private NotificationService notifications;
    private TenantInviteService invites;
    private TenantActivityRecorder activities;
    private StringRedisTemplate redis;
    private UserMapper users;
    private TenantApprovalService service;

    @BeforeEach
    void setUp() throws Exception {
        database = new EmbeddedDatabaseBuilder().generateUniqueName(true)
                .setType(EmbeddedDatabaseType.H2).build();
        jdbc = new JdbcTemplate(database);
        jdbc.execute("""
                CREATE TABLE t_tenant_join_request (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    request_id BIGINT NOT NULL UNIQUE,
                    tenant_id BIGINT NOT NULL,
                    user_id BIGINT NOT NULL,
                    invite_id BIGINT NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    reviewed_by BIGINT,
                    review_comment VARCHAR(255),
                    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    reviewed_at TIMESTAMP
                )
                """);
        MybatisConfiguration configuration = new MybatisConfiguration();
        configuration.setMapUnderscoreToCamelCase(true);
        configuration.addMapper(TenantJoinRequestMapper.class);
        configuration.addMapper(UserMapper.class);
        MybatisSqlSessionFactoryBean factory = new MybatisSqlSessionFactoryBean();
        factory.setDataSource(database);
        factory.setConfiguration(configuration);
        requests = spy(new SqlSessionTemplate(Objects.requireNonNull(factory.getObject()))
                .getMapper(TenantJoinRequestMapper.class));

        TenantValidationHelper validation = mock(TenantValidationHelper.class);
        TenantDO tenant = new TenantDO();
        tenant.setTenantId(20L);
        tenant.setName("当前团队");
        when(validation.validateTenantTeamActive(eq(20L), any())).thenReturn(tenant);
        memberships = mock(UserTenantService.class);
        when(memberships.isUserJoinedTenant(anyLong(), eq(20L))).thenReturn(true);
        when(memberships.createUserTenant(30L, 20L, "MEMBER")).thenReturn(true);
        notifications = mock(NotificationService.class);
        invites = mock(TenantInviteService.class);
        activities = mock(TenantActivityRecorder.class);
        redis = mock(StringRedisTemplate.class);
        users = mock(UserMapper.class);
        TenantApprovalServiceImpl target = new TenantApprovalServiceImpl(requests, validation,
                memberships, redis, notifications, invites, users, mock(TenantInviteMapper.class), activities);
        ProxyFactory proxy = new ProxyFactory(target);
        proxy.addAdvice(new TransactionInterceptor(new DataSourceTransactionManager(database),
                new AnnotationTransactionAttributeSource()));
        service = (TenantApprovalService) proxy.getProxy();
    }

    @AfterEach
    void tearDown() {
        if (database != null) {
            database.shutdown();
        }
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void foreignTenantRequestIsNotFoundAndHasNoSideEffects(boolean approve) {
        insertRequest(40L, 21L, 30L, "PENDING");

        assertClientError(TenantErrorCodeEnum.REQUEST_NOT_FOUND, approve, 10L, 40L);

        assertUnreviewed(40L);
        assertNoReviewSideEffects();
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void missingRequestHasSameErrorAsForeignTenantRequest(boolean approve) {
        assertClientError(TenantErrorCodeEnum.REQUEST_NOT_FOUND, approve, 10L, 999L);
        assertNoReviewSideEffects();
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void sameTenantReviewSucceedsOnceAndLeavesOtherTenantUntouched(boolean approve) {
        insertRequest(40L, 20L, 30L, "PENDING");
        insertRequest(41L, 21L, 31L, "PENDING");

        assertTrue(review(approve, 10L, 40L));

        assertEquals(approve ? "APPROVED" : "REJECTED", status(40L));
        assertEquals(10L, jdbc.queryForObject(
                "SELECT reviewed_by FROM t_tenant_join_request WHERE request_id = 40", Long.class));
        assertNotNull(jdbc.queryForObject(
                "SELECT reviewed_at FROM t_tenant_join_request WHERE request_id = 40", java.sql.Timestamp.class));
        assertUnreviewed(41L);
        assertClientError(TenantErrorCodeEnum.REQUEST_HAS_BEEN_REVIEWED, approve, 10L, 40L);
        verify(activities).record(eq(20L), any());
        verify(notifications).publishNotification(eq(20L), eq("SYSTEM"), eq("INFO"),
                anyString(), anyString(), isNull(), eq(List.of(30L)));
        verify(redis).delete(RedisKeyConstant.TENANT_JOIN_REQUEST_KEY + 40L);
        if (approve) {
            verify(memberships).createUserTenant(30L, 20L, "MEMBER");
            verify(invites).incrementUsageCount(9L);
        } else {
            verify(memberships, never()).createUserTenant(anyLong(), anyLong(), anyString());
            verifyNoInteractions(invites);
            assertEquals("暂不批准", jdbc.queryForObject(
                    "SELECT review_comment FROM t_tenant_join_request WHERE request_id = 40", String.class));
        }
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void applicantCannotReviewOwnRequest(boolean approve) {
        insertRequest(40L, 20L, 10L, "PENDING");
        assertClientError(TenantErrorCodeEnum.REQUEST_APPROVE_SELF_ERROR, approve, 10L, 40L);
        assertUnreviewed(40L);
        assertNoReviewSideEffects();
    }

    @ParameterizedTest
    @CsvSource({"true, APPROVED", "true, REJECTED", "false, APPROVED", "false, REJECTED"})
    void reviewedRequestCannotBeChanged(boolean approve, String existingStatus) {
        insertRequest(40L, 20L, 30L, existingStatus);
        assertClientError(TenantErrorCodeEnum.REQUEST_HAS_BEEN_REVIEWED, approve, 10L, 40L);
        assertEquals(existingStatus, status(40L));
        assertNoReviewSideEffects();
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void revokedMembershipCannotReview(boolean approve) {
        insertRequest(40L, 20L, 30L, "PENDING");
        when(memberships.isUserJoinedTenant(10L, 20L)).thenReturn(false);
        assertClientError(TenantErrorCodeEnum.TENANT_NOT_JOINED, approve, 10L, 40L);
        assertUnreviewed(40L);
        assertNoReviewSideEffects();
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void staleOwnershipSnapshotCannotUpdateAnotherTenantsRow(boolean approve) {
        insertRequest(40L, 21L, 30L, "PENDING");
        TenantJoinRequestDO snapshot = new TenantJoinRequestDO();
        snapshot.setRequestId(40L);
        snapshot.setTenantId(20L);
        snapshot.setUserId(30L);
        snapshot.setInviteId(9L);
        snapshot.setStatus("PENDING");
        // 独立验证写入边界：即使前置读取提供了旧归属，数据库更新也必须限定租户。
        doReturn(snapshot).when(requests).selectOne(any());

        ServerException error = assertThrows(ServerException.class, () -> review(approve, 10L, 40L));

        assertEquals(TenantErrorCodeEnum.REQUEST_STATUS_UPDATE_ERROR.code(), error.getErrorCode());
        assertUnreviewed(40L);
        assertNoReviewSideEffects();
    }

    @Test
    void membershipFailureRollsBackApprovedStatus() {
        insertRequest(40L, 20L, 30L, "PENDING");
        when(memberships.createUserTenant(30L, 20L, "MEMBER")).thenReturn(false);
        ServerException error = assertThrows(ServerException.class, () -> review(true, 10L, 40L));
        assertEquals(TenantErrorCodeEnum.TENANT_JOIN_ERROR.code(), error.getErrorCode());
        assertUnreviewed(40L);
        verifyNoInteractions(activities, notifications, invites, redis, users);
    }

    private void insertRequest(long requestId, long tenantId, long applicantId, String status) {
        jdbc.update("""
                INSERT INTO t_tenant_join_request(request_id, tenant_id, user_id, invite_id, status)
                VALUES (?, ?, ?, 9, ?)
                """, requestId, tenantId, applicantId, status);
    }

    private Boolean review(boolean approve, long operatorId, long requestId) {
        TenantJoinRejectReqDTO rejection = new TenantJoinRejectReqDTO();
        rejection.setReviewComment("暂不批准");
        return approve ? service.approveJoinRequest(operatorId, 20L, requestId)
                : service.rejectJoinRequest(operatorId, 20L, requestId, rejection);
    }

    private void assertClientError(TenantErrorCodeEnum code, boolean approve, long operatorId, long requestId) {
        ClientException error = assertThrows(ClientException.class, () -> review(approve, operatorId, requestId));
        assertEquals(code.code(), error.getErrorCode());
    }

    private String status(long requestId) {
        return jdbc.queryForObject("SELECT status FROM t_tenant_join_request WHERE request_id = ?",
                String.class, requestId);
    }

    private void assertUnreviewed(long requestId) {
        assertEquals("PENDING", status(requestId));
        assertNull(jdbc.queryForObject("SELECT reviewed_by FROM t_tenant_join_request WHERE request_id = ?",
                Long.class, requestId));
        assertNull(jdbc.queryForObject("SELECT reviewed_at FROM t_tenant_join_request WHERE request_id = ?",
                java.sql.Timestamp.class, requestId));
        assertNull(jdbc.queryForObject("SELECT review_comment FROM t_tenant_join_request WHERE request_id = ?",
                String.class, requestId));
    }

    private void assertNoReviewSideEffects() {
        verify(memberships, never()).createUserTenant(anyLong(), anyLong(), anyString());
        verifyNoInteractions(activities, notifications, invites, redis, users);
    }
}
