-- 独立 MySQL 测试夹具：维护发送记录的最终结构，不执行生产 migration。
CREATE TABLE IF NOT EXISTS t_sms_send_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '发送记录主键',
    request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '调用方幂等请求标识',
    request_fingerprint VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '带pepper的请求摘要',
    scene VARCHAR(64) NOT NULL COMMENT '服务端发信业务场景',
    user_id BIGINT NULL COMMENT '可信业务用户',
    tenant_id BIGINT NULL COMMENT '可信业务租户',
    provider VARCHAR(16) NOT NULL COMMENT '实际服务商',
    recipient_encrypted VARCHAR(2048) NOT NULL COMMENT '收件人AES-GCM密文',
    recipient_hash VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '收件人带pepper查询哈希',
    status VARCHAR(16) NOT NULL COMMENT 'QUEUED/SUBMITTING/ACCEPTED/REJECTED/UNKNOWN/EXPIRED；不表示送达',
    provider_request_id VARCHAR(128) NULL COMMENT '服务商请求标识',
    provider_message_id VARCHAR(128) NULL COMMENT '服务商消息或回执标识',
    error_code VARCHAR(128) NULL COMMENT '脱敏协议错误码',
    duration_ms BIGINT NULL COMMENT '调用耗时毫秒',
    create_time DATETIME(3) NOT NULL COMMENT '持久化受理时间',
    update_time DATETIME(3) NOT NULL COMMENT '最后更新记录时间',
    sign_name VARCHAR(50) NOT NULL COMMENT '短信签名',
    template_code VARCHAR(64) NOT NULL COMMENT '模板代码',
    payload_encrypted MEDIUMTEXT NULL COMMENT '短期任务载荷AES-GCM密文，终态清空',
    deadline_at DATETIME(3) NULL COMMENT '任务执行截止时间',
    next_attempt_at DATETIME(3) NULL COMMENT '下次允许认领时间',
    attempt_count INT NOT NULL DEFAULT 0 COMMENT '已认领执行次数',
    execution_token VARCHAR(64) NULL COMMENT '本次执行CAS标识',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sms_send_request (request_id),
    KEY idx_sms_send_recipient_time (recipient_hash, create_time),
    KEY idx_sms_send_status_time (status, create_time),
    KEY idx_sms_task_due (status, next_attempt_at, id),
    KEY idx_sms_task_deadline (status, deadline_at),
    KEY idx_sms_task_stale (status, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信服务商调用记录，不表示送达';

CREATE TABLE IF NOT EXISTS t_email_send_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '发送记录主键',
    request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '调用方幂等请求标识',
    request_fingerprint VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '带pepper的请求摘要',
    scene VARCHAR(64) NOT NULL COMMENT '服务端发信业务场景',
    user_id BIGINT NULL COMMENT '可信业务用户',
    tenant_id BIGINT NULL COMMENT '可信业务租户',
    provider VARCHAR(16) NOT NULL COMMENT '实际服务商',
    recipient_encrypted VARCHAR(2048) NOT NULL COMMENT '收件人AES-GCM密文',
    recipient_hash VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '收件人带pepper查询哈希',
    status VARCHAR(16) NOT NULL COMMENT 'QUEUED/SUBMITTING/ACCEPTED/REJECTED/UNKNOWN/EXPIRED；不表示送达',
    provider_request_id VARCHAR(128) NULL COMMENT '服务商请求标识',
    provider_message_id VARCHAR(128) NULL COMMENT '服务商消息或回执标识',
    error_code VARCHAR(128) NULL COMMENT '脱敏协议错误码',
    duration_ms BIGINT NULL COMMENT '调用耗时毫秒',
    create_time DATETIME(3) NOT NULL COMMENT '持久化受理时间',
    update_time DATETIME(3) NOT NULL COMMENT '最后更新记录时间',
    subject_hash VARCHAR(64) NOT NULL COMMENT '主题带pepper摘要',
    payload_encrypted MEDIUMTEXT NULL COMMENT '短期任务载荷AES-GCM密文，终态清空',
    deadline_at DATETIME(3) NULL COMMENT '任务执行截止时间',
    next_attempt_at DATETIME(3) NULL COMMENT '下次允许认领时间',
    attempt_count INT NOT NULL DEFAULT 0 COMMENT '已认领执行次数',
    execution_token VARCHAR(64) NULL COMMENT '本次执行CAS标识',
    PRIMARY KEY (id),
    UNIQUE KEY uk_email_send_request (request_id),
    KEY idx_email_send_recipient_time (recipient_hash, create_time),
    KEY idx_email_send_status_time (status, create_time),
    KEY idx_email_task_due (status, next_attempt_at, id),
    KEY idx_email_task_deadline (status, deadline_at),
    KEY idx_email_task_stale (status, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='邮件服务商调用记录，不表示送达';
